version: '2.1'
services:
  archivemanager-app:
    image: archivemanager
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - POSTGRES_HOST=archivemanager-postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD
      - KEY_STORE_PASSWORD
    volumes:
      - ${VOLUMES_ARCHIVEMANAGER_PATH}/config:/home/config
    working_dir: /home
    ports:
      - 443:443
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/management/health']
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 40s
  archivemanager-postgresql:
    extends:
      file: postgresql.yml
      service: archivemanager-postgresql
