version: '2.1'
services:
  archivemanager-app:
    image: archivemanager:${TAG_ARCH_MGN}
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - POSTGRES_HOST=archivemanager-postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD
      - KEY_STORE_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ${CONFIG_VOLUMES_ARCHIVEMANAGER_PATH}:/home/archivemanager/config
      - ${LOGS_VOLUMES_ARCHIVEMANAGER_PATH}:/home/archivemanager/logs
      - ${STS_VOLUMES_ARCHIVEMANAGER_PATH}:/home/STS
      - ${LTS_VOLUMES_ARCHIVEMANAGER_PATH}:/home/LTS
    working_dir: /home/archivemanager
    user: ${USER_ARCHIVEMANAGER_ID}:${GROUP_ARCHIVEMANAGER_ID}
    ports:
      - 443:8080
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '--insecure', '--silent', '--fail', '--output', '/dev/null', 'https://127.0.0.1:8080/management/health']
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 40s
    #mem_limit: 1224m
    #mem_reservation: 512m
    #cpus: 4
  archivemanager-postgresql:
    image: postgres:12.1
    volumes:
      - ${POSTGRES_VOLUMES_ARCHIVEMANAGER_PATH}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    ports:
      - 5432:5432
